/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as RestApiImport } from './routes/rest-api';
import { Route as IndexImport } from './routes/index';

// Create/Update Routes

const RestApiRoute = RestApiImport.update({
  id: '/rest-api',
  path: '/rest-api',
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/rest-api': {
      id: '/rest-api';
      path: '/rest-api';
      fullPath: '/rest-api';
      preLoaderRoute: typeof RestApiImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/rest-api': typeof RestApiRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/rest-api': typeof RestApiRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/rest-api': typeof RestApiRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/rest-api';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/rest-api';
  id: '__root__' | '/' | '/rest-api';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  RestApiRoute: typeof RestApiRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RestApiRoute: RestApiRoute,
};

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/rest-api"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/rest-api": {
      "filePath": "rest-api.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
